name: Verify

on: [push]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: ESLint
        run: npm run lint
      - name: Prettier
        run: npm run pretty

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
